version: '3.1'

services:
  # Backend service
  backend:
    build: ./tradehive-backend
    container_name: tradehive-backend
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=your-secret-key
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - tradehive-network

  # PostgreSQL service
  db:
    image: postgres:latest
    container_name: tradehive-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin.10
      POSTGRES_DB: tradehive
    ports:
      - "5431:5432"
    volumes:
      - /storage:/var/lib/postgresql/data
    networks:
      - tradehive-network
networks:
  tradehive-network:
    driver: bridge

